### ISSUE TITLE
Adding tasks via the Quire API does not automatically update devices app and website

### ISSUE THREAD

**Issue by criticc** [quire-api/quire-api#38]
To see this just create a task via the quire api and update it to the specific board, then check your browser in the already opened board page, if there is your task, creating them manually automatically updates every member phone app and website.

To see tasks created by the API we need to refresh the page.

**Comment by cor3000** [comment]
I just retested this, and the task showed up in the board immediately without any refresh.

[add-task-to-board.mp4.zip](https://github.com/quire-api/quire-api/files/4473495/add-task-to-board.mp4.zip)

Can you please try again?

**Comment by criticc** [comment]
i can't really download your video it always fail with network error, i've tested and it works on list view but not on board view.

Check this video, test5 works well on list view, test8 does not work well on board view just after a refresh.

https://mega.nz/file/A003xQTI#G5v4aREJsS1KG_hhxFx2zCEU6JiuihN7XHCajAbzdxQ

**Comment by cor3000** [comment]
I was able to download/ watch your video, however it doesn't show which requests you are posting to produce this unexpected behavior, so that's nothing we can actually test.

I also successfully downloaded my previous video from multiple netoworks successfully. 
Just to be sure I uploaded it also to a different location 
https://send.firefox.com/download/767429d5c323ac54/#oSrL864qhpdAHnfWBTmxEg (this link is valied for 7 days 20 downloads max).

It shows which JSON payloads, I am actually sending and to which quire-api endpoint URLs, so you can replay this case on your side to see whether this case works for you. 
Maybe you can spot the difference and post the relevant information here, so we can reproduce the case, and provide a fix or recommended usage.

For this test I use Chrome #81 on linux mint in case that's relevant (maybe different browsers behave differently)

**Comment by criticc** [comment]
ok, ive seen your video seems to work, and right after, i identified my problem, the problem was on the first request creating the task i was setting "status" field to 1 which makes this strange behavior, since there is no column for status = 1, maybe this should be changed auto to the first column status when the board field is changed (if that status does not exist in any column of the board).

thanks for your time,
criticc

**Comment by cor3000** [comment]
Thanks for the details I can confirm the case, even though the status is correctly truncated to 0 to match the board column, the task doesn't show up without a manual browser refresh.
